name: Greet new contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Thanks for opening your first issue! Please make sure you have filled
            in all the relevant details. If you have a question rather than a bug
            or feature request, the [Home Assistant Community Forum](https://community.home-assistant.io/t/input-boolean-groups/996318)
            is a good place to get help.
          pr-message: >
            Thanks for your first pull request! A maintainer will review it as
            soon as possible.
